### ISSUE TITLE
AutoDebris crashing on Quest 2 while playing DLC Songs

### ISSUE THREAD

**Issue by steamgineer** [Lauriethefish/AutoDebris#1]
I'm not sure if there were any other DLC packs that caused this issue, but songs from the Monstercat DLC pack would crash when selected to play. If they were the first song you selected when opening Beat Saber, they would play and preview, but if you selected another song after them, Beat Saber.  I turned off mods one by one until it stopped crashing, and then turned on all mods except AutoDebris and tried with just the core mods, and AutoDebris installed to verify that AutoDebris was causing the crashes. I fully reinstalled Beat Saber and my mods to make sure it wasn't a corrupted file.  The problem started  2-21-21. I hadn't noticed a problem before then.

**Comment by Lauriethefish** [comment]
Hello, I need a log file to give me more information about this crash. I don't own any DLC packs, so can't test it myself xP
Here are the instructions for fetching a log file:

**1)** Copy and paste the following into your file browser's address bar:
`%appdata%\SideQuest\platform-tools`
Make sure that you have a file named adb or adb.exe
**2)** Hold shift, and while holding, right click somewhere blank in that folder
**3)** Click 'Open command prompt' or 'Open PowerShell' 
**4)** Connect your Quest to your computer
**5)** Write `.\adb.exe logcat > logcat.log` in that command line window that was opened and press enter 
Leave that window opened, and start the game on the Quest (while it is connected to your PC)
**6)** Then, play/fail a song, or any other thing that you need to get a log for, and take off your Quest
**7)** You can now close the command line window that you opened before
**8)** A file named `logcat.log` will be in the folder you opened first
**9)** Drag and drop that file into Discord to upload the log file
